version: "3.8"

services:
  frontend:
    container_name: event-calendar-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 80:3000
    environment:
      - REACT_APP_BASE_URL=https://calendar.mysibsau.ru:8000/v1/
    networks:
      - event-calendar
    command: "npm start"

networks:
  event-calendar:
    external: True
    name: event-calendar
